forum/config/routes.rb
Rails.application.routes.draw do

  root 'posts#index'
  
  resources :posts, only: [:index, :show, :create]
  resources :comments, only: [:create] 
  get '/comments/new/(:parent_id)', to: 'comments#new', as: :new_comment
  get '/reply/new/(:post_id)', to: 'comments#new', as: :new_reply
  

end

forum/app/models/comment.rb
require 'obscenity/active_model'

class Comment < ActiveRecord::Base
  belongs_to :post
  attr_accessor :tree
  acts_as_tree order: 'created_at DESC'
  validates :comment,  obscenity: { sanitize: true, replacement: :vowels }, presence: true
end

forum/app/models/post.rb
class Post < ActiveRecord::Base
  validates :subject, presence: true
  has_many :comments, dependent: :destroy
  paginates_per 10
end

forum/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

forum/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    if params[:parent_id]
      parent = Comment.find(params[:parent_id])
      @comment = Comment.new(parent_id: params[:parent_id],post_id: parent.post_id )
    else
      @comment = Comment.new(post_id: params[:post_id])
    end
  end
    
  def create
    if params[:comment][:parent_id].to_i > 0
       parent = Comment.find_by_id(params[:comment].delete(:parent_id))
       @comment = parent.children.build(comment_params)
     else
       @comment = Comment.new(comment_params)
     end
 
     if @comment.save
       flash[:success] = 'Your comment was successfully added!'
       redirect_to post_path(@comment.post)
     else
       render 'new'
     end
  end
  
  private
  def comment_params
    params.require(:comment).permit(:comment,:post_id)
  end
end

forum/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order(created_at: :asc).page params[:page]
  end

  def show
    @post = Post.find(params[:id])    
    @comments = @post.comments.hash_tree
  end
  
  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = 'Your post was successfully created!'
      redirect_to @post
    else
      render 'new'
    end
  end
  
  private 
  def post_params
    params.require(:post).permit(:subject)
  end
end

forum/app/helpers/application_helper.rb
module ApplicationHelper
end

forum/app/helpers/comments_helper.rb
module CommentsHelper
  def comments_tree_for(comments, tree)
    comments.map do |comment, nested_comments|
      comment.tree =  "#{tree}.#{comment.id}"
      render(comment) +
      (nested_comments.size > 0 ? content_tag(:div, comments_tree_for(nested_comments,"#{tree}.#{comment.id}"), class: "replies") : nil)
    end.join.html_safe
  end
end

forum/app/views/comments/_comment.html.erb
<div class="well">
  <blockquote>
		<p>
		  <strong><%= "#{comment.tree}" %></strong>
			<span> <%= "#{comment.created_at.strftime('%D %T')} #{comment.comment}" %> </span>
		</p>
  </blockquote>
	
  <% from_reply_form ||= nil %>
  <% unless from_reply_form %>
    <p><%= link_to 'reply', new_comment_path(comment.id) %></p>
  <% end %>
</div>

forum/app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :parent_id %>

  <div>
		<%= f.hidden_field :post_id, value: @comment.post_id  %> 
	</div>
	
  <div>
    <%= f.label :comment %>
    <%= f.text_area :comment, required: true %>
  </div>

  <%= f.submit %>
<% end %>

forum/app/views/comments/new.html.erb
<h1>New comment</h1>

<% if @comment.parent %>
  <%= render 'comment', comment: @comment.parent, from_reply_form: true %>
<% end %>

<%= render 'form' %>

forum/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Forum</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

forum/app/views/posts/index.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<% @posts.each do |post| %>
	<p>
		<%= link_to "#{post.id}. #{post.created_at.strftime("%D %T")}", post_path(post) %> 
		<span><%= post.subject %></span>
	</p>
<% end %>

<%= paginate @posts %>

forum/app/views/posts/new.html.erb
<%= form_for :post, url: posts_path do |f| %>
  <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited
      this post from being saved:</h2>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
  <p>
    <%= f.label :subject %><br>
    <%= f.text_field :subject %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', posts_path %>

forum/app/views/posts/show.html.erb
<%= link_to 'Home', posts_path %>

<p>
  <strong><%= @post.id %></strong>
	<span> <%= "#{@post.created_at.strftime('%D %T')} #{@post.subject}" %> </span>	
  <p><%= link_to 'reply', new_reply_path(@post.id) %></p>
</p>

<%= comments_tree_for @comments,@post.id %>